#167484548 Users should be able to Login to Authors Haven
andela/coding-geeks-ah-frontend pull request #10
Opened 2019-10-03 20:36 UTC by harerakalex

### What does this PR do?
- Users should be able to Login to Authors Haven
### Description of Task to be completed?
- Implement login functionalities
- Implement logout functionalities
### How should this be manually tested?
- Clone this branch
- `npm install` to install all dependencies
- `npm start` to run the server
- Use this route `http://localhost:3000/login` to go to the login page
- Use these credential to login 
  - Email: carlos@gmail.com
  - Password: User1234

2019-10-04 10:06 UTC, placideirandora requested changes
1. I think you should place the text in the middle.
<img width="366" alt="Screen Shot 2019-10-04 at 11 33 27" src="https://user-images.githubusercontent.com/34879554/66197548-e1d9a500-e69a-11e9-8d2e-e3290ef871c3.png">

2. I think you should remove the blue border when the input box is in focus mode as well as leaving some space before the placeholder text for good design.
<img width="368" alt="Screen Shot 2019-10-04 at 11 35 18" src="https://user-images.githubusercontent.com/34879554/66197755-5a406600-e69b-11e9-9b70-23364c44883f.png">

3. I think those social login buttons should be real buttons because I can see that only the text is clickable but the rest cannot be clicked. It is rather a background color.
<img width="351" alt="Screen Shot 2019-10-04 at 11 38 51" src="https://user-images.githubusercontent.com/34879554/66197987-befbc080-e69b-11e9-9f11-109def8d167b.png">

4. I think font-size on the page should page consistent and meaningful for catching the user attention and user experience.
<img width="944" alt="Screen Shot 2019-10-04 at 11 43 24" src="https://user-images.githubusercontent.com/34879554/66198287-5fea7b80-e69c-11e9-9c1e-7cb1c8dc00d9.png">

5. I think you should improve the iPad responsiveness so that the buttons cannot wrap to the next line.
<img width="522" alt="Screen Shot 2019-10-04 at 11 46 14" src="https://user-images.githubusercontent.com/34879554/66198422-afc94280-e69c-11e9-811f-a32e7c08e78b.png">

6. I think you should remove the following blue border on the button when it is clicked (in the focus mode).
<img width="246" alt="Screen Shot 2019-10-04 at 11 49 00" src="https://user-images.githubusercontent.com/34879554/66198603-0fbfe900-e69d-11e9-9cd0-346a6d30b76d.png">

7. I think you should position the notification model in the middle for user experience.
<img width="1281" alt="Screen Shot 2019-10-04 at 11 51 29" src="https://user-images.githubusercontent.com/34879554/66198729-53b2ee00-e69d-11e9-9f1d-2f7cf9ea1ba8.png">

2019-10-04 18:27 UTC, placideirandora approved these changes

2019-10-07 00:51 UTC, clemwek approved these changes
LGTM

2019-10-07 05:53 UTC, Jkadhuwa requested changes
Can you please add a login link in the navbar component for the unauthenticated user.

2019-10-07 08:16 UTC, Jkadhuwa approved these changes

2019-10-07 09:12 UTC, merged