#167484547 Users should be presented with a reset password
andela/coding-geeks-ah-frontend pull request #12
Opened 2019-10-09 15:53 UTC by raymond42

### What does this PR do?
- Users should be presented with a reset password
### Description of Task to be completed?
- Implement forgot password functionalities
- Implement reset password functionalities
### How should this be manually tested?
- Clone this branch
- `npm install` to install all dependencies
- `npm start` to run the server
- Use this route `http://localhost:3000/forgot` to go to the login page
- N.B Provide a valid email
- Check your email and use the link sent to you to reset your password

### What are the relevant pivotal tracker stories?
- [changing the reset password link to fronted url](https://www.pivotaltracker.com/story/show/169040218)

2019-10-10 18:58 UTC, placideirandora requested changes
1. I checked and found out that you didn't write end to end tests for your feature, password reset. You should write some.

2. I think you should increase the size of the input bottom border to match the one of the login and signup.

3. I think you should also increase the size of the placeholder text to match the one of the login and signup.

<img width="933" alt="Screen Shot 2019-10-10 at 20 41 47" src="https://user-images.githubusercontent.com/34879554/66597220-cdb40d00-eb9e-11e9-958a-e5e75a7536e4.png">

4.  I think you should align the signup button with the other elements for consistency.
<img width="1180" alt="Screen Shot 2019-10-10 at 20 45 13" src="https://user-images.githubusercontent.com/34879554/66597288-f63c0700-eb9e-11e9-8831-168b36b41658.png">

5. I think you should place the content in the center.
<img width="1143" alt="Screen Shot 2019-10-10 at 20 46 12" src="https://user-images.githubusercontent.com/34879554/66597379-24b9e200-eb9f-11e9-922f-6e3de13bd772.png">

6. I think you should improve the responsiveness of smartphones. I have checked with: Galaxy S5, Pixel 2, and iPhone 4 (and all iPhone versions).
<img width="378" alt="Screen Shot 2019-10-10 at 20 49 17" src="https://user-images.githubusercontent.com/34879554/66597624-a27ded80-eb9f-11e9-9b73-ae31baf9582d.png">
<img width="343" alt="Screen Shot 2019-10-10 at 20 49 07" src="https://user-images.githubusercontent.com/34879554/66597634-a873ce80-eb9f-11e9-8cbe-83a1917a3860.png">
<img width="423" alt="Screen Shot 2019-10-10 at 20 49 27" src="https://user-images.githubusercontent.com/34879554/66597636-a873ce80-eb9f-11e9-8c42-65e7c498e688.png">

7. You should also improve the responsiveness of tablets. The size should decrease to reflect on the screen width. As you can see, the button text 'Reset Password' has wrapped. It should be on the same line.
<img width="455" alt="Screen Shot 2019-10-10 at 20 52 01" src="https://user-images.githubusercontent.com/34879554/66597856-115b4680-eba0-11e9-9239-bd7608b356ee.png">

8. You should fix the following bug: When I try to reset my password, I get the message: Network error.
<img width="1401" alt="Screen Shot 2019-10-10 at 20 57 55" src="https://user-images.githubusercontent.com/34879554/66598148-aeb67a80-eba0-11e9-943b-eaf3e1f41c4e.png">

2019-10-11 08:46 UTC, raymond42 commented
> 1. I checked and found out that you didn't write end to end tests for your feature, password reset. You should write some.
> 2. I think you should increase the size of the input bottom border to match the one of the login and signup.
> 3. I think you should also increase the size of the placeholder text to match the one of the login and signup.
> 
> <img alt="Screen Shot 2019-10-10 at 20 41 47" width="933" src="https://user-images.githubusercontent.com/34879554/66597220-cdb40d00-eb9e-11e9-958a-e5e75a7536e4.png">
> 
> 1. I think you should align the signup button with the other elements for consistency.
> 
> <img alt="Screen Shot 2019-10-10 at 20 45 13" width="1180" src="https://user-images.githubusercontent.com/34879554/66597288-f63c0700-eb9e-11e9-8831-168b36b41658.png">
> 
> 1. I think you should place the content in the center.
> 
> <img alt="Screen Shot 2019-10-10 at 20 46 12" width="1143" src="https://user-images.githubusercontent.com/34879554/66597379-24b9e200-eb9f-11e9-922f-6e3de13bd772.png">
> 
> 1. I think you should improve the responsiveness of smartphones. I have checked with: Galaxy S5, Pixel 2, and iPhone 4 (and all iPhone versions).
> 
> <img alt="Screen Shot 2019-10-10 at 20 49 17" width="378" src="https://user-images.githubusercontent.com/34879554/66597624-a27ded80-eb9f-11e9-9b73-ae31baf9582d.png">
> 
> <img alt="Screen Shot 2019-10-10 at 20 49 07" width="343" src="https://user-images.githubusercontent.com/34879554/66597634-a873ce80-eb9f-11e9-8cbe-83a1917a3860.png">
> 
> <img alt="Screen Shot 2019-10-10 at 20 49 27" width="423" src="https://user-images.githubusercontent.com/34879554/66597636-a873ce80-eb9f-11e9-8c42-65e7c498e688.png">
> 
> 1. You should also improve the responsiveness of tablets. The size should decrease to reflect on the screen width. As you can see, the button text 'Reset Password' has wrapped. It should be on the same line.
> 
> <img alt="Screen Shot 2019-10-10 at 20 52 01" width="455" src="https://user-images.githubusercontent.com/34879554/66597856-115b4680-eba0-11e9-9239-bd7608b356ee.png">
> 
> 1. You should fix the following bug: When I try to reset my password, I get the message: Network error.
> 
> <img alt="Screen Shot 2019-10-10 at 20 57 55" width="1401" src="https://user-images.githubusercontent.com/34879554/66598148-aeb67a80-eba0-11e9-943b-eaf3e1f41c4e.png">

@placideirandora I implemented your feedback. Thank you

2019-10-11 08:49 UTC, placideirandora requested changes
1. After getting the password reset link and clicked on it, I didn't get a page for resetting my password, instead, I was presented with an empty page. You should fix this.
<img width="1117" alt="Screen Shot 2019-10-11 at 10 46 55" src="https://user-images.githubusercontent.com/34879554/66638242-db0bde80-ec14-11e9-9483-1f9e21af0ca4.png">
<img width="1440" alt="Screen Shot 2019-10-11 at 10 46 43" src="https://user-images.githubusercontent.com/34879554/66638241-db0bde80-ec14-11e9-8acf-efcc137b4b97.png">

2019-10-12 14:15 UTC, raymond42 commented
> 1. After getting the password reset link and clicked on it, I didn't get a page for resetting my password, instead, I was presented with an empty page. You should fix this.
> 
> <img alt="Screen Shot 2019-10-11 at 10 46 55" width="1117" src="https://user-images.githubusercontent.com/34879554/66638242-db0bde80-ec14-11e9-9483-1f9e21af0ca4.png">
> 
> <img alt="Screen Shot 2019-10-11 at 10 46 43" width="1440" src="https://user-images.githubusercontent.com/34879554/66638241-db0bde80-ec14-11e9-8acf-efcc137b4b97.png">

Thanks. fixed

2019-10-14 04:26 UTC, harerakalex approved these changes
LGTM

2019-10-14 11:04 UTC, clemwek approved these changes
Fix the small changes then merge

2019-10-14 11:04 UTC, clemwek commented on src/feature/Reset Password/forgot password/ForgotPasswordComponent.js
> +  onChange = (e) => {
Use `event` in full.

2019-10-14 11:04 UTC, clemwek commented on src/feature/Reset Password/forgot password/ForgotPasswordComponent.js
> +  onSubmit = (e) => {
Use `event` in full

2019-10-14 11:06 UTC, raymond42 commented on src/feature/Reset Password/forgot password/ForgotPasswordComponent.js
> +  onChange = (e) => {
on it

2019-10-14 11:06 UTC, raymond42 commented on src/feature/Reset Password/forgot password/ForgotPasswordComponent.js
> +  onSubmit = (e) => {
on it

2019-10-14 11:29 UTC, merged