#167484555 User should be able to like and dislike articles
andela/coding-geeks-ah-frontend pull request #24
Opened 2019-10-24 20:06 UTC by Jkadhuwa

### What does this PR do?
- Enable authenticated users to like and dislike articles
### Description of Task to be completed?
- Create UI for Viewing single article and like and disliking articles.
- Connect the UI to the backend API
- Test the functionality

### How should this be manually tested?
- Clone this branch
- `npm install` to install all dependencies
- `npm start` to run the server
- `Signup or login to like or dislike articles`
- On the Home page, select any article and proceed to click the like or dislike buttons

### What are the relevant pivotal tracker stories?
- [Like or Dislike Articles](https://www.pivotaltracker.com/story/show/167484555)

2019-10-25 05:35 UTC, harerakalex approved these changes
LGTM

2019-10-25 07:32 UTC, raymond42 approved these changes
Looks fine

2019-10-25 07:32 UTC, malaba6 approved these changes

2019-10-25 09:58 UTC, placideirandora approved these changes
Looks good!

2019-10-26 13:52 UTC, bdushimi requested changes

2019-10-26 13:52 UTC, bdushimi commented on src/app/App.js
> +          <ProtectedRoutes path="/Create" component={CreateArticle} />
@Jkadhuwa path or route names should be in lowercase

2019-10-26 13:52 UTC, bdushimi commented on src/app/App.js
>            <Route path="/Signup" component={SignUp} />
@Jkadhuwa path or route names should be in lowercase

2019-10-26 13:52 UTC, bdushimi commented on src/app/App.js
> +          {/* // <Route path="/articles/:slug" component={SingleArticle} /> */}
@Jkadhuwa You can remove this commented line if it's not used.

2019-10-26 13:52 UTC, bdushimi commented on src/app/App.js
>            <Route path="/Signup" component={SignUp} />
@Jkadhuwa duplicated signup routes, kindly remove one of them.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/__tests__/CreateArticleAction.test.js
> +  });
@Jkadhuwa any reason to why this PR for liking and disliking an article introduces changes in files of createArticle feature which are not related?

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/createArticle/CreateArticleComponent.js
> +// import Home from '../../homePage/Home';
Kindly remove commented codes

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/getArticles/GetAllArticlesComponent.js
> +        {/* <Home /> */}
Kindly remove commented codes

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/getSingleArticle/GetSingleArticleReducer.js
> +    case DISLIKE_ARTICLE_SUCCESS:
@Jkadhuwa any reason to why you're checking if some actions got dispatched and don't update the state. A reducer should always return a new state.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/getSingleArticle/GetSingleArticleReducer.js
> +    case DISLIKE_ARTICLE_FAIL:
@Jkadhuwa any reason to why you're checking if some actions got dispatched and don't update the state. A reducer should always return a new state.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/LikeDislikeAction.js
> +  };
@Jkadhuwa wouldn't be better if such axiosConfiguration is centralized i.e. put in a file and get imported wherever and whenever one needs them?

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/LikeDislikeAction.js
> +  };
@Jkadhuwa wouldn't be better if such axiosConfiguration is centralized i.e. put in a file and get imported wherever and whenever one needs them? As you can see from lines 7-15 and 34 - 41, it is duplicated.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/LikeDislikeComponent.js
> +  { likeArticle, dislikeArticle }
@Jkadhuwa while passing this object which contains functions/action creators works, I suggest you use mapDispatchProps function instead.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeAction.test.js
> +    expect(dispatchedActions[1].type).toEqual(expected.type);
@Jkadhuwa This is test is not written correctly. You should ascertain whether store.getActions() equals expectedAction.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeAction.test.js
> +    expect(dispatchedTypes[0]).toEqual(expected);
@Jkadhuwa How many actions that got dispatched when disliking an article? if there're more than one, when asserting, you should expect store.getActions().toEqual(Array of those expected Actions).

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeAction.test.js
> +    expect(dispatchedTypes[2]).toEqual(expected);
@Jkadhuwa How many actions that got dispatched when disliking an article? if there're more than one, when asserting, you should expect store.getActions().toEqual(Array of those expected Actions).

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeComponent.test.js
> +describe('Get All Articles Components tests', () => {
@Jkadhuwa the first parameter of the describe block is the name of the component under test. The component under test is LikeDislikeComponent, not GetAllArticlesComponent.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeComponent.test.js
> +  it('Should render a form inputs', () => {
@Jkadhuwa There're no inputs elements in LikeDislikeComponent, therefore, this test description is misleading, Kindly update.

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeComponent.test.js
> +});
@Jkadhuwa All of the tests descriptions is this file are similar! Are they testing the same thing?

2019-10-26 13:52 UTC, bdushimi commented on src/feature/articles/likeDislikeArticles/__tests__/LikeDislikeComponent.test.js
> +    dislikeArticle.at(1).simulate('click');
@Jkadhuwa what are you expecting? The click event got simulated and nothing else! There're no assertions. It's the same for the above 3 tests, You should expect whether handleLike/handleDislike got called.

2019-10-29 15:04 UTC, Jkadhuwa commented on src/feature/articles/getSingleArticle/GetSingleArticleReducer.js
> +    case DISLIKE_ARTICLE_SUCCESS:
They all do the same thing so I combined them. It works as an OR operator.

2019-10-29 15:05 UTC, Jkadhuwa commented
@bdushimi I have finished implementing the feedback

2019-10-29 15:21 UTC, placideirandora requested changes
1. When I click on the like and dislike buttons while trying to view a single article, I get an error: **jwt malformed.** You should fix that.
<img width="1440" alt="Screen Shot 2019-10-29 at 17 17 52" src="https://user-images.githubusercontent.com/34879554/67781718-794ecf80-fa70-11e9-85b5-1174b9feb4cb.png">
<img width="1440" alt="Screen Shot 2019-10-29 at 17 17 45" src="https://user-images.githubusercontent.com/34879554/67781715-794ecf80-fa70-11e9-9dd1-8822916bacba.png">

2. I expect to start reading an article from the top (start with its title). But when click on an article (or the second one), the reading position starts in the middle and hides the article. You should fix that.
<img width="1440" alt="Screen Shot 2019-10-29 at 17 23 48" src="https://user-images.githubusercontent.com/34879554/67782215-2de8f100-fa71-11e9-84e1-02cd342ceac2.png">
<img width="1440" alt="Screen Shot 2019-10-29 at 17 24 02" src="https://user-images.githubusercontent.com/34879554/67782219-2e818780-fa71-11e9-8285-a2e3525292e7.png">

3. As you left a space between the navigation bar and the article (body), you should at the bottom as well.
<img width="1440" alt="Screen Shot 2019-10-29 at 17 30 13" src="https://user-images.githubusercontent.com/34879554/67783064-57564c80-fa72-11e9-998f-35b780442fec.png">

<img width="1440" alt="Screen Shot 2019-10-29 at 17 30 20" src="https://user-images.githubusercontent.com/34879554/67783076-5f15f100-fa72-11e9-800f-8d5ce9aa2f14.png">

4. I think the colors should be consistent with each other. Currently, Some elements are in black and others in blue.
<img width="1440" alt="Screen Shot 2019-10-29 at 17 30 20" src="https://user-images.githubusercontent.com/34879554/67783360-cfbd0d80-fa72-11e9-9f67-41d8883d5cdc.png">

5. I think the toast messages for liking/disliking and removing a like/dislike should have different background colors for the user to determine the difference easily.
<img width="407" alt="Screen Shot 2019-10-29 at 17 42 40" src="https://user-images.githubusercontent.com/34879554/67783998-c1232600-fa73-11e9-9e47-debe3ba34104.png">

2019-10-29 17:51 UTC, Jkadhuwa commented
@placideirandora 
    - On `tags` that is just a placeholder as I was not working on it. 
    - On the colors, the likes are displayed as success and dislikes are displayed as a warning.

2019-10-29 18:35 UTC, placideirandora commented
> @placideirandora
> - On `tags` that is just a placeholder as I was not working on it.
> - On the colors, the likes are displayed as success and dislikes are displayed as a warning.

Well, I have removed the tags' feedback. Try to find a way to customize the colors. If there isn't any. I will remove that feedback as well.

2019-10-30 10:51 UTC, malaba6 requested changes
Check the responsiveness on the mobile phone. This is what I got on a `Galaxy5` device
<img width="362" alt="Screen Shot 2019-10-30 at 12 48 47" src="https://user-images.githubusercontent.com/50101879/67851781-d51e6480-fb13-11e9-816d-1bfaaa564315.png">

2019-10-30 11:00 UTC, placideirandora approved these changes

2019-10-30 11:33 UTC, bdushimi approved these changes

2019-10-30 11:59 UTC, merged